### ISSUE TITLE
Jobs with invalid image should fail way faster

### ISSUE THREAD

**Issue by kkaarreell** [testing-farm/artemis#3]
Not sure if this is the right place, anyway...
When I run `testing-farm request ...` with an invalid image it takes quite a long time (like 1 or 2 hours?) before it aborts. I think Testing Farm / Artemis should know what images are available and fail way faster.

**Comment by brakogh** [comment]
+1 Right now, my job that was scheduled  on non-existing compose is already running for 4 hours now. I was not able to find out what was a problem from logs and I never thought it could be missing compose because of time duration.

**Comment by psss** [comment]
I guess, the gitlab repo would be better place:

 * https://gitlab.com/testing-farm/artemis/-/issues

Is that right, @thrix?

**Comment by kkaarreell** [comment]
Closing this one, it has been tracked in Jira as TFT-1723 and resolved
